# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Akipe
tagline:             'Akp-web'
description:         'Le site web d'Akipe/AKP, Julien Milletre, curieux et passionné de numérique.'
url:                 https://akipe.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Julien Milletre
  url:               https://akipe.tech
  email:             emailtest@test.com

# Custom vars
version:             1.0.0
